name: Terraform Plan
on: pull_request

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

defaults:
  run:
    working-directory: terraform

jobs:
  tflint:
    name: tflint
    runs-on: ubuntu-latest
    container: wata727/tflint
    steps:
    - uses: actions/checkout@v2
    - run: tflint

  terraform_fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    needs: tflint
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - run: terraform fmt -check -recursive

  terraform_plan:
    name: terraform plan
    runs-on: ubuntu-latest
    needs: terraform_fmt
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform initiate
      run: terraform init

    - name: Terraform plan
      run: terraform plan -var-file="env/${{ github.base_ref }}.tfvars" -out=${{ github.workspace }}/terraform.plan

    # There is a bug with Checkov, so we need to create a JSON
    # version of the plan for it.
    - name: Create JSON of plan
      shell: bash
      run: terraform show -json ${{ github.workspace }}/terraform.plan > ${{ github.workspace }}/terraform.plan.json

    - name: Upload plan to artifact
      uses: actions/upload-artifact@v2
      with:
        name: plan
        path: ${{ github.workspace }}/terraform.plan*

  checkov:
    name: Running Checkov
    runs-on: ubuntu-latest
    environment: prod
    needs: terraform_plan
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: actions/download-artifact@v2
        with:
          name: plan
          path: ${{ github.workspace }}

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ github.workspace }}
          framework: terraform