name: Terraform Code Test
on: pull_request

defaults:
  run:
    shell: pwsh
    working-directory: terraform

jobs:
  tflint:
    name: tflint
    runs-on: ubuntu-latest
    container: wata727/tflint
    steps:
    - uses: actions/checkout@v2
    - run: tflint

  terraform_fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - run: terraform fmt -check -recursive

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


  # checkov:
  #   name: Running Checkov
  #   runs-on: ubuntu-latest
  #   environment: prod
  #   needs: terraform_plan
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.8

  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: plan
  #         path: ${{ github.workspace }}

  #     - name: Test with Checkov
  #       id: checkov
  #       uses: bridgecrewio/checkov-action@master
  #       with:
  #         directory: ${{ github.workspace }}
  #         framework: terraform